<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuthTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthTokenRepository extends EntityRepository
{

    public function deleteByUserId(int $userId): void
    {
        $qb = $this->createQueryBuilder('at');
        $qb->innerJoin('at.user', 'usr')
            ->where($qb->expr()->eq('at.user', $userId))
            ->delete()
            ->getQuery()->execute();
    }
}
