<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductSpecificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductSpecificationRepository extends EntityRepository
{

}
