<?php

namespace App\Repository;

use App\Entity\User;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    /**
     * @param string $roleName
     * @return User[]
     */
    public function findByRoleName(string $roleName): array
    {
        return $this->createQueryBuilder('u')
            ->innerJoin('u.roles', 'r')
            ->where('r.role = :roleName')
            ->setParameter('roleName', $roleName)
            ->getQuery()
            ->execute();
    }

    /**
     * @param string $userOrEmail
     * @return User|null
     * @throws NonUniqueResultException
     */
    function findByUsernameOrEmail(string $userOrEmail): ?User
    {
        $qb = $this->createQueryBuilder('u');
        return $qb
            ->where('u.username = :username')
            ->orWhere('u.email = :username')
            ->setParameter('username', $userOrEmail)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
