contacts:
    email: plasticam@abv.bg
    phoneNumber: '0888494116'
    whatsapp: '359888494116'
    facebook: 'https://www.facebook.com/plastican'
    youtube: 'https://www.youtube.com/channel/UCwA0bp5DjX6nelAQDin8Inw'
