#index:
#    path: /
#    controller: App\Controller\DefaultController::index
global:
  path: /{req}
  defaults: { _controller: 'App\Controller\HomeController::index' }
  requirements:
    req: "^(?!\/?api).*"